# Generated by Django 3.2.7 on 2023-01-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_userprofile_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ifd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='sherlock.jpg', upload_to='images')),
            ],
        ),
    ]
